# -*- coding: utf-8 -*-
"""SIVAN_CODE_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHj9DmJ23CkkxRGR9CMKz_H1GuU1TWmZ
"""

# @title


import requests
import json
import time
import os
from enum import Enum
from datetime import datetime
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, asdict
import hashlib
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

# =============================================================================
# CONFIGURATION & ENUMS
# =============================================================================

class Severity(Enum):
    CRITICAL = 3
    MEDIUM = 2
    MINOR = 1
    NONE = 0

class ReviewStatus(Enum):
    APPROVED = "APPROVED"
    NEEDS_REVISION = "NEEDS_REVISION"
    NEEDS_REDESIGN = "NEEDS_REDESIGN"

@dataclass
class APIConfig:
    """Secure API configuration - NO HARDCODED KEYS"""

    BASE_URL: str = "https://lightning.ai/api/v1/chat/completions"

    # Keys loaded securely
    PLANNER_API_KEY: str = None
    WORKER_API_KEY: str = None
    REVIEWER_API_KEY: str = None

    PLANNER_MODEL: str = "lightning-ai/kimi-k2.5"
    WORKER_MODEL: str = "anthropic/claude-sonnet-4-5-20250929"
    REVIEWER_MODEL: str = "openai/gpt-4.1"

    COST_PER_1K_TOKENS: Dict[str, float] = None

    def __post_init__(self):
        if self.COST_PER_1K_TOKENS is None:
            self.COST_PER_1K_TOKENS = {
                "lightning-ai/kimi-k2.5": 0.0001,
                "anthropic/claude-sonnet-4-5-20250929": 0.00014,
            }

    @classmethod
    def from_env(cls):
        """Load from environment (production)"""
        return cls(
            PLANNER_API_KEY=os.getenv("PLANNER_API_KEY"),
            WORKER_API_KEY=os.getenv("WORKER_API_KEY"),
            REVIEWER_API_KEY=os.getenv("REVIEWER_API_KEY")
        )

    @classmethod
    def from_keys(cls, planner_key: str, worker_key: str, reviewer_key: str):
        """Load from keys (development)"""
        return cls(
            PLANNER_API_KEY=planner_key,
            WORKER_API_KEY=worker_key,
            REVIEWER_API_KEY=reviewer_key
        )

# =============================================================================
# STRUCTURED RESPONSE MODELS
# =============================================================================

@dataclass
class ReviewResult:
    """Structured review - NO TEXT PARSING"""
    status: str
    severity: str
    critical_issues: List[str]
    medium_issues: List[str]
    minor_issues: List[str]
    architectural_concerns: List[str]
    specific_fixes: List[str]
    redesign_recommendation: Optional[str]
    positive_aspects: List[str]

    def to_dict(self):
        return asdict(self)

@dataclass
class CostMetrics:
    """Track API costs"""
    total_cost: float = 0.0
    planner_cost: float = 0.0
    worker_cost: float = 0.0
    reviewer_cost: float = 0.0
    total_tokens: int = 0

    def add_cost(self, agent: str, tokens: int, cost: float):
        self.total_cost += cost
        self.total_tokens += tokens
        if agent == "planner":
            self.planner_cost += cost
        elif agent == "worker":
            self.worker_cost += cost
        elif agent == "reviewer":
            self.reviewer_cost += cost

# =============================================================================
# AUDIT LOGGER
# =============================================================================

class AuditLogger:
    """Persistent audit logging"""

    def __init__(self, log_file: str = "agent_audit.jsonl"):
        self.log_file = log_file
        self.session_id = hashlib.md5(str(datetime.now()).encode()).hexdigest()[:8]

    def log(self, event_type: str, data: dict):
        entry = {
            "timestamp": datetime.now().isoformat(),
            "session_id": self.session_id,
            "event_type": event_type,
            "data": data
        }
        with open(self.log_file, "a") as f:
            f.write(json.dumps(entry) + "\n")

    def log_api_call(self, agent: str, model: str, prompt_length: int, response_length: int, cost: float):
        self.log("api_call", {
            "agent": agent,
            "model": model,
            "prompt_length": prompt_length,
            "response_length": response_length,
            "cost": cost
        })

    def log_iteration(self, iteration: int, status: str, severity: str):
        self.log("iteration", {"iteration": iteration, "status": status, "severity": severity})

    def log_redesign(self, redesign_count: int, reason: str):
        self.log("redesign", {"redesign_count": redesign_count, "reason": reason})

# =============================================================================
# RETRY & BACKOFF
# =============================================================================

def exponential_backoff_retry(func, max_retries: int = 3, base_delay: float = 1.0):
    """Retry with exponential backoff"""
    for attempt in range(max_retries):
        try:
            return func()
        except Exception as e:
            if attempt == max_retries - 1:
                raise
            delay = base_delay * (2 ** attempt)
            print(f"Retry {attempt + 1}/{max_retries} after {delay}s: {str(e)}")
            time.sleep(delay)

# =============================================================================
# API CALLER WITH METRICS
# =============================================================================

def call_ai_api_with_metrics(
    model_name: str,
    api_key: str,
    prompt: str,
    temperature: float,
    config: APIConfig,
    audit_logger: AuditLogger,
    agent_name: str,
    timeout: int = 300
) -> Tuple[str, float, int]:
    """API call with timeout, retry, cost tracking, audit logging"""

    def api_call():
        # Create the base payload that all models accept
        payload = {
            "model": model_name,
            "messages": [{"role": "user", "content": [{"type": "text", "text": prompt}]}],
            "temperature": 1.0
        }

        # Only add the extra beta parameters if it is NOT an Anthropic model
        if "anthropic" not in model_name.lower():
            payload["top_p"] = 1.0
            payload["n"] = 1
            payload["presence_penalty"] = 0.0
            payload["frequency_penalty"] = 0.0

        response = requests.post(
            url=config.BASE_URL,
            headers={"Authorization": api_key, "Content-Type": "application/json"},
            data=json.dumps(payload),
            timeout=timeout
        )

        if response.status_code != 200:
            raise Exception(f"API Error {response.status_code}: {response.text}")

        response_data = json.loads(response.content)

        if 'choices' in response_data:
            content = response_data['choices'][0]['message']['content']
            tokens = response_data.get('usage', {}).get('total_tokens', len(prompt) // 4 + len(content) // 4)
        else:
            content = response_data.get('content', str(response_data))
            tokens = len(prompt) // 4 + len(content) // 4

        cost_per_token = config.COST_PER_1K_TOKENS.get(model_name, 0.0001) / 1000
        cost = tokens * cost_per_token

        audit_logger.log_api_call(agent_name, model_name, len(prompt), len(content), cost)

        return content, cost, tokens

    try:
        return exponential_backoff_retry(api_call)
    except Exception as e:
        print(f"CRITICAL: API failed: {str(e)}")
        return f"ERROR: {str(e)}", 0.0, 0

# =============================================================================
# AGENTS
# =============================================================================

class PlannerAgent:
    """Architect and planner - DOES NOT GENERATE CODE"""

    def __init__(self, config: APIConfig, audit_logger: AuditLogger):
        self.config = config
        self.audit_logger = audit_logger

    def create_plan(self, task_description: str, codebase_context: str = "", redesign_feedback: Optional[str] = None) -> Dict:
        """Creates ONLY architectural plan - NO CODE GENERATION"""

        if redesign_feedback:
            prompt = f"""You are a SENIOR SOFTWARE ARCHITECT. Your role is PLANNING ONLY - NOT coding.\n\nThe previous implementation approach FAILED with these issues:\n{redesign_feedback}\n\nORIGINAL TASK: {task_description}\n\nYOUR JOB: Design a COMPLETELY DIFFERENT architectural approach.\n\n⚠️ IMPORTANT: You are NOT writing code. You are making architectural decisions.\n\nRESPOND WITH THIS EXACT STRUCTURE (NO CODE):\n\n## Root Cause Analysis\n[THINKING SPACE: Why did the previous approach fail? What was the fundamental mistake? Analyze the trade-offs before proposing a new solution.]\n\n## New Architectural Strategy\n[High-level design paradigm - describe the approach, don't implement it]\n\n## Technology Stack\n[Specific libraries/frameworks to use]\n- Library 1: [name] - Purpose: [why use it]\n- Library 2: [name] - Purpose: [why use it]\n\n## Component Breakdown\n[List of classes/functions needed - just names and responsibilities, NO implementation]\n1. Component Name: Responsibility\n2. Component Name: Responsibility\n\n## Implementation Roadmap\n[Step-by-step tasks for the Worker agent to execute]\nStep 1: [What to build]\nStep 2: [What to build]\nStep 3: [What to build]\n\n## Security Requirements\n[What security measures must be implemented]\n\n## Edge Cases to Handle\n[List specific edge cases]\n\n## Success Criteria\n[How to verify the implementation works]\n\n⚠️ DO NOT WRITE ANY CODE. Your output is architectural guidance for the Worker agent."""

        else:
            prompt = f"""You are an EXPERT SOFTWARE ARCHITECT. Your role is PLANNING & ARCHITECTURE ONLY - NOT coding.\n\nTASK TO ARCHITECT: {task_description}\n\nEXISTING CODEBASE CONTEXT: {codebase_context if codebase_context else "New project - starting from scratch"}\n\nYOUR JOB: Create a comprehensive architectural plan that the Worker agent will implement.\n\n⚠️ CRITICAL: You are NOT writing code. You are designing the architecture and breaking down the work.\n\nRESPOND WITH THIS EXACT STRUCTURE (NO CODE BLOCKS):\n\n## Technical Analysis\n[THINKING SPACE: Analyze the core problem. What are the major technical hurdles? Discuss trade-offs between different approaches (e.g., sync vs async, database choices). Make your architectural decisions here before writing the blueprint below.]\n\n## Architecture Overview\n[High-level design approach - describe the chosen solution architecture based on your analysis]\n\n## Technology Stack & Libraries\n[Specific libraries to use - be precise! Base this on your analysis.]\n- Library 1: [exact name] - Purpose: [what it does]\n- Library 2: [exact name] - Purpose: [what it does]\nExample: "email-validator" for email validation (safer than regex)\n\n## Component Design\n[Classes/functions needed - just structure, NO implementation]\n1. ClassName/FunctionName\n   - Purpose: [what it does]\n   - Inputs: [what parameters]\n   - Outputs: [what it returns]\n   - Dependencies: [what it needs]\n
2. ClassName/FunctionName\n   - Purpose: [what it does]\n   - Inputs: [what parameters]\n   - Outputs: [what it returns]\n
## Implementation Tasks (for Worker Agent)\n[Detailed step-by-step breakdown - actionable tasks]\nTask 1: [Specific instruction for Worker]\nTask 2: [Specific instruction for Worker]\nTask 3: [Specific instruction for Worker]\n
## Security Considerations\n[Security requirements the Worker must implement]\n- Requirement 1: [what must be secured and how]\n
## Edge Cases & Error Handling\n[Specific scenarios to handle]\n- Edge case 1: [scenario] → [how to handle]\n
## Testing Strategy\n[What should be tested]\n
## Success Criteria\n[How to verify correctness]\n
⚠️ REMEMBER: You are the architect, not the builder. Provide the blueprint, not the construction.\n⚠️ DO NOT INCLUDE ANY CODE SNIPPETS OR IMPLEMENTATIONS.\n⚠️ Focus on WHAT to build and WHY, not HOW to build it."""

        plan, cost, tokens = call_ai_api_with_metrics(
            self.config.PLANNER_MODEL, self.config.PLANNER_API_KEY,
            prompt, 0.7, self.config, self.audit_logger, "planner"
        )

        print("=" * 80)
        print("🏗️  PLANNER AGENT - ARCHITECTURAL PLAN" + (" (REDESIGN)" if redesign_feedback else ""))
        print("=" * 80)
        print(plan)
        print(f"\n💰 Cost: ${cost:.6f} | Tokens: {tokens}")
        print("=" * 80 + "\n")

        return {"plan": plan, "task": task_description, "is_redesign": bool(redesign_feedback), "cost": cost}


class WorkerAgent:
    def __init__(self, config: APIConfig, audit_logger: AuditLogger):
        self.config = config
        self.audit_logger = audit_logger

    def write_code(self, plan_data: Dict, feedback: Optional[str] = None, iteration: int = 1, priority_fixes: Optional[str] = None) -> Tuple[str, float]:
        if feedback and priority_fixes:
            prompt = f"""CRITICAL fixes required.\n\nTASK: {plan_data['task']}\nPLAN: {plan_data['plan']}\nCRITICAL: {priority_fixes}\nFEEDBACK: {feedback}\n\nINSTRUCTIONS:\n- Implement the requested fixes.\n- Use type hints and add brief, highly technical docstrings.\n- Output ONLY valid code. No conversational filler."""
        elif feedback:
            prompt = f"""Revise code.\n\nTASK: {plan_data['task']}\nFEEDBACK: {feedback}\n\nOutput ONLY corrected code."""
        else:
            prompt = f"""Implement.\n\nTASK: {plan_data['task']}\nPLAN: {plan_data['plan']}\n\nUse libraries. Production code. Use type hints and add brief, highly technical docstrings"""

        code, cost, tokens = call_ai_api_with_metrics(
            self.config.WORKER_MODEL, self.config.WORKER_API_KEY,
            prompt, 0.2, self.config, self.audit_logger, "worker"
        )

        print("=" * 80)
        print(f"WORKER - Iteration {iteration}")
        print("=" * 80)
        print(code)
        print(f"Cost: ${cost:.6f} | Tokens: {tokens}\n")

        return code, cost


class ReviewerAgent:
    def __init__(self, config: APIConfig, audit_logger: AuditLogger):
        self.config = config
        self.audit_logger = audit_logger

    def review_code(self, code: str, original_task: str, iteration: int = 1) -> Dict:
        prompt = f"""ROLE: Senior Site Reliability Engineer (SRE) & Chaos Monkey.
         RESPOND WITH JSON ONLY.

           MISSION: You are reviewing code for a high-throughput architecture. Assume this code will run in a hostile environment on severely constrained hardware (limited RAM, CPU, and battery) rather than a pristine cloud cluster. Your sole objective is to BREAK the code by hunting for memory leaks, resource exhaustion, race conditions, and unhandled edge cases.

         TASK: {original_task}
            CODE: {code}

JSON FORMAT:
            {{
  "status": "APPROVED/NEEDS_REVISION/NEEDS_REDESIGN",
  "severity": "CRITICAL/MEDIUM/MINOR/NONE",
  "critical_issues": ["Focus exclusively on: OOM (Out of Memory) risks, whole-file loading vs streaming, thread/DB locks, unhandled exceptions in async loops"],
  "medium_issues": ["Focus on: Inefficient batching, missing network/DB retries, N+1 query problems"],
  "minor_issues": ["Focus on: Poor observability/logging context, hardcoded limits"],
  "architectural_concerns": ["Focus on: Systemic scaling bottlenecks, lack of defensive boundaries"],
  "specific_fixes": ["Actionable code replacement 1", "Actionable code replacement 2"],
  "redesign_recommendation": "Provide specific architectural patterns (e.g., Global Queues, Circuit Breakers) if NEEDS_REDESIGN else null",
  "positive_aspects": ["good1", "good2"]
}}

RULES:
1. Output ONLY valid JSON. No markdown wrappers outside the JSON.
2. NEEDS_REDESIGN must be triggered if the fundamental approach will crash under heavy concurrent load.
3. CRITICAL severity is reserved for code that will physically exhaust system resources (RAM/CPU/Disk).
4. Do not rubber-stamp "Happy Path" code. Demand defensive programming.
5. Recommend specific production-grade libraries (e.g., 'tenacity' for retries, 'asyncio.Queue' for batching)."""

        review_text, cost, tokens = call_ai_api_with_metrics(
            self.config.REVIEWER_MODEL, self.config.REVIEWER_API_KEY,
            prompt, 0.3, self.config, self.audit_logger, "reviewer"
        )

        print("=" * 80)
        print(f"REVIEWER - Iteration {iteration}")
        print("=" * 80)

        try:
            if "```json" in review_text:
                start = review_text.find("```json") + 7
                end = review_text.find("```", start)
                json_str = review_text[start:end].strip()
            elif "```" in review_text:
                start = review_text.find("```") + 3
                end = review_text.find("```", start)
                json_str = review_text[start:end].strip()
            else:
                json_str = review_text.strip()

            review_data = json.loads(json_str)

            # FIX: Ensure all fields are lists of strings
            def ensure_string_list(value):
                if isinstance(value, list):
                    return [str(item) if not isinstance(item, str) else item for item in value]
                elif isinstance(value, str):
                    return [value]
                else:
                    return []

            review_data['critical_issues'] = ensure_string_list(review_data.get('critical_issues', []))
            review_data['medium_issues'] = ensure_string_list(review_data.get('medium_issues', []))
            review_data['minor_issues'] = ensure_string_list(review_data.get('minor_issues', []))
            review_data['architectural_concerns'] = ensure_string_list(review_data.get('architectural_concerns', []))
            review_data['specific_fixes'] = ensure_string_list(review_data.get('specific_fixes', []))
            review_data['positive_aspects'] = ensure_string_list(review_data.get('positive_aspects', []))

            # Ensure redesign_recommendation is string or None
            if 'redesign_recommendation' in review_data:
                if review_data['redesign_recommendation'] == "null":
                    review_data['redesign_recommendation'] = None

            review = ReviewResult(**review_data)
        except Exception as e:
            print(f"WARNING: Failed to parse JSON review: {e}")
            print(f"Raw response: {review_text[:500]}...")
            # Fallback
            review = ReviewResult(
                status="NEEDS_REVISION", severity="MEDIUM",
                critical_issues=["Failed to parse JSON review"],
                medium_issues=[], minor_issues=[],
                architectural_concerns=[],
                specific_fixes=["Request properly formatted JSON from reviewer"],
                redesign_recommendation=None, positive_aspects=[]
            )

        print(json.dumps(review.to_dict(), indent=2))
        print(f"Cost: ${cost:.6f} | Tokens: {tokens}\n")

        approved = review.status == "APPROVED"
        needs_redesign = review.status == "NEEDS_REDESIGN" or (
            review.severity == "CRITICAL" and len(review.architectural_concerns) > 0
        )

        severity_map = {
            "CRITICAL": Severity.CRITICAL,
            "MEDIUM": Severity.MEDIUM,
            "MINOR": Severity.MINOR,
            "NONE": Severity.NONE
        }
        severity = severity_map.get(review.severity, Severity.MEDIUM)

        self.audit_logger.log_iteration(iteration, review.status, review.severity)

        # FIX: Safely join critical_issues (now guaranteed to be strings)
        critical_issues_text = "\n".join(review.critical_issues) if review.critical_issues else ""

        return {
            "approved": approved,
            "needs_redesign": needs_redesign,
            "feedback": json.dumps(review.to_dict(), indent=2),
            "severity": severity,
            "critical_issues": critical_issues_text,  # FIX: Now safe to join
            "structured_review": review,
            "iteration": iteration,
            "cost": cost
        }


# =============================================================================
# ELITE ORCHESTRATOR
# =============================================================================

class EliteCodingAgentOrchestrator:
    def __init__(self, config: APIConfig, max_iterations: int = 3, max_redesigns: int = 2, timeout_per_agent: int = 60, audit_log_file: str = "agent_audit.jsonl"):
        self.config = config
        self.max_iterations = max_iterations
        self.max_redesigns = max_redesigns
        self.timeout = timeout_per_agent

        self.audit_logger = AuditLogger(audit_log_file)
        self.cost_metrics = CostMetrics()

        self.planner = PlannerAgent(config, self.audit_logger)
        self.worker = WorkerAgent(config, self.audit_logger)
        self.reviewer = ReviewerAgent(config, self.audit_logger)

    def execute_task(self, task_description: str, codebase_context: str = "") -> Dict:
        print("ELITE AI CODING AGENT")
        print("=" * 80)
        print(f"Task: {task_description}")
        print(f"Session: {self.audit_logger.session_id}\n")
        redesign_count = 0
        plan_data = None

        while redesign_count <= self.max_redesigns:
            if redesign_count == 0:
                print("PHASE 1: PLANNING\n")
                plan_data = self.planner.create_plan(task_description, codebase_context)
                self.cost_metrics.add_cost("planner", 0, plan_data["cost"])

            code = None
            review_result = None
            previous_severity = Severity.NONE

            for iteration in range(1, self.max_iterations + 1):
                print(f"ITERATION {iteration}/{self.max_iterations}")
                print("-" * 80 + "\n")

                priority_fixes = review_result.get('critical_issues') if review_result else None
                feedback = review_result.get('feedback') if review_result and not review_result['approved'] else None

                code, worker_cost = self.worker.write_code(plan_data, feedback, iteration, priority_fixes)
                self.cost_metrics.add_cost("worker", 0, worker_cost)

                review_result = self.reviewer.review_code(code, task_description, iteration)
                self.cost_metrics.add_cost("reviewer", 0, review_result["cost"])

                if review_result['approved']:
                    print("=" * 80)
                    print("APPROVED - PRODUCTION READY!")
                    print("=" * 80)
                    self._print_cost_summary()
                    return self._build_result(code, review_result, iteration, redesign_count, plan_data, True, "SUCCESS")

                elif review_result['needs_redesign']:
                    print("=" * 80)
                    print("CRITICAL ARCHITECTURAL ISSUE")
                    print("=" * 80)

                    redesign_feedback = f"SEVERITY: {review_result['severity'].name}\nCRITICAL: {review_result['critical_issues']}"
                    self.audit_logger.log_redesign(redesign_count + 1, review_result['critical_issues'])
                    plan_data = self.planner.create_plan(task_description, codebase_context, redesign_feedback)
                    self.cost_metrics.add_cost("planner", 0, plan_data["cost"])
                    redesign_count += 1
                    break

                previous_severity = review_result['severity']

        self._print_cost_summary()
        return self._build_result(code, review_result, self.max_iterations, redesign_count, plan_data, False, "FAILED")

    def _build_result(self, code, review_result, iterations, redesigns, plan_data, approved, status):
        return {
            "final_code": code, "review": review_result,
            "iterations_used": iterations, "redesigns_used": redesigns,
            "plan": plan_data['plan'], "approved": approved, "status": status,
            "cost_metrics": asdict(self.cost_metrics), "audit_log": self.audit_logger.log_file
        }

    def _print_cost_summary(self):
        print("\n" + "=" * 80)
        print("COST SUMMARY")
        print("=" * 80)
        print(f"Total: ${self.cost_metrics.total_cost:.6f}")
        print(f"Planner: ${self.cost_metrics.planner_cost:.6f}")
        print(f"Worker: ${self.cost_metrics.worker_cost:.6f}")
        print(f"Reviewer: ${self.cost_metrics.reviewer_cost:.6f}")
        print(f"Tokens: {self.cost_metrics.total_tokens:,}")
        print("=" * 80)


print("✅ ELITE SYSTEM LOADED!")
print("\n🏆 FEATURES:")
print("  ✓ NO hardcoded secrets")
print("  ✓ Structured JSON output")
print("  ✓ Retry + backoff")
print("  ✓ Cost tracking")
print("  ✓ Timeout handling")
print("  ✓ Audit logging")
print("  ✓ Graceful degradation")

# Recreate the agent to use the new class

# Define the API configuration using the previously defined keys
config = APIConfig.from_env()

agent = EliteCodingAgentOrchestrator(
    config=config,
    max_iterations=3,
    max_redesigns=2,
    audit_log_file="test_audit.jsonl"
)

print("✅ Agent recreated with fixed ReviewerAgent!")

# @title
# ============================================================================
# SMART CONTEXT MANAGEMENT SYSTEM - FIXED VERSION
# Add this as a NEW CELL in your notebook
# ============================================================================

import re
from typing import Dict, Optional, List, Tuple
from dataclasses import dataclass
import hashlib
from datetime import datetime

# ============================================================================
# CONTEXT CONFIGURATION
# ============================================================================

@dataclass
class ContextLimits:
    """Configuration for context management"""
    max_prompt_tokens: int = 60000
    max_code_length: int = 200000
    max_feedback_length: int = 8000
    keep_iterations: int = 1


# ============================================================================
# CONTEXT MANAGER
# ============================================================================

class ContextManager:
    """Intelligently manage context across iterations"""

    def __init__(self, limits: ContextLimits = None):
        self.limits = limits or ContextLimits()
        self.iteration_history = []

    def estimate_tokens(self, text: str) -> int:
        """Rough token estimation (1 token ≈ 4 chars)"""
        return len(str(text)) // 4

    def truncate_text(self, text: str, max_length: int) -> str:
        """Truncate text to max length"""
        if len(text) <= max_length:
            return text
        return text[:max_length] + "\n... [truncated for brevity]"

    def extract_critical_issues(self, feedback: str) -> str:
        """Extract only CRITICAL issues from review"""

        if not feedback:
            return "No feedback provided."

        # Try to find CRITICAL ISSUES section
        if "CRITICAL ISSUES" in feedback.upper():
            try:
                start = feedback.upper().find("CRITICAL ISSUES")
                end = feedback.upper().find("MEDIUM ISSUES", start)
                if end == -1:
                    end = feedback.upper().find("MINOR ISSUES", start)
                if end == -1:
                    end = len(feedback)

                critical_section = feedback[start:end].strip()
                return critical_section[:self.limits.max_feedback_length]
            except:
                pass

        # Fallback: Return first part of feedback
        return self.truncate_text(feedback, 500)

    def extract_specific_fixes(self, feedback: str) -> str:
        """Extract actionable fix instructions"""

        if not feedback:
            return "No specific fixes provided."

        # Try to find SPECIFIC FIXES section
        if "SPECIFIC FIXES" in feedback.upper():
            try:
                start = feedback.upper().find("SPECIFIC FIXES")
                end = feedback.upper().find("REDESIGN", start)
                if end == -1:
                    end = len(feedback)

                fixes_section = feedback[start:end].strip()
                return fixes_section[:self.limits.max_feedback_length]
            except:
                pass

        return "See critical issues above for what to fix."

    def prepare_iteration_context(
        self,
        task: str,
        plan: str,
        previous_code: Optional[str],
        feedback: Optional[str],
        iteration: int,
        priority_fixes: Optional[str] = None
    ) -> Tuple[str, Dict]:
        """Prepare optimized context for Worker agent"""

        metadata = {
            'iteration': iteration,
            'included_code': False,
            'included_feedback': False,
            'tokens_estimate': 0
        }

        # ITERATION 1: Fresh start
        if iteration == 1:
            prompt = f"""You are an expert Python developer. Implement this coding task.\n\nTASK:\n{task}\n\nIMPLEMENTATION PLAN:\n{self.truncate_text(plan, 2000)}\n\nMANDATORY REQUIREMENTS:\n- Follow the plan architecture EXACTLY\n- Use recommended libraries from the plan\n- Include comprehensive error handling\n- Add type hints and detailed docstrings\n- Handle all edge cases mentioned\n- Write production-ready, secure code\n- NO quick hacks or unsafe patterns\n\nIf using external libraries, add installation comments.\n\nOutput ONLY the Python code wrapped in ```python code blocks.\n"""
            metadata['tokens_estimate'] = self.estimate_tokens(prompt)
            return prompt, metadata

        # ITERATION 2+: Include previous code + focused feedback
        code_to_include = previous_code or ""
        if len(code_to_include) > self.limits.max_code_length:
            code_to_include = self.truncate_text(code_to_include, self.limits.max_code_length)

        metadata['included_code'] = bool(previous_code)

        # Prepare focused feedback
        if priority_fixes:
            focused_feedback = f"PRIORITY FIXES:\n{priority_fixes}"
            metadata['included_feedback'] = True
        elif feedback:
            critical = self.extract_critical_issues(feedback)
            fixes = self.extract_specific_fixes(feedback)
            focused_feedback = f"{critical}\n\n{fixes}"
            metadata['included_feedback'] = True
        else:
            focused_feedback = "No specific feedback - improve code quality."

        focused_feedback = self.truncate_text(focused_feedback, self.limits.max_feedback_length)

        prompt = f"""You are an expert Python developer. REVISE the code based on reviewer feedback.\n\nORIGINAL TASK:\n{task}\n\nPREVIOUS CODE (Iteration {iteration - 1}):\n```python\n{code_to_include}\nISSUES DETECTED:\n{focused_feedback}\n\nINSTRUCTIONS:\n\nFix ALL issues mentioned in the feedback\n\nPrioritize security and correctness over cleverness\n\nUse established libraries where recommended\n\nInclude comments explaining fixes\n\nProvide ONLY the complete, corrected Python code\n\nOutput clean, working Python code wrapped in ```python code blocks.\n"""
        metadata['tokens_estimate'] = self.estimate_tokens(prompt)

        return prompt, metadata

    def log_iteration(self, iteration: int, prompt_tokens: int, code_length: int):
        """Track iteration history"""
        self.iteration_history.append({
            'iteration': iteration,
            'prompt_tokens': prompt_tokens,
            'code_length': code_length
        })

    def get_context_summary(self) -> Dict:
        """Get summary of context usage"""
        if not self.iteration_history:
            return {
                'total_iterations': 0,
                'total_tokens_used': 0,
                'avg_tokens_per_iteration': 0
            }

        total_tokens = sum(h['prompt_tokens'] for h in self.iteration_history)

        return {
            'total_iterations': len(self.iteration_history),
            'total_tokens_used': total_tokens,
            'avg_tokens_per_iteration': total_tokens / len(self.iteration_history),
            'iterations': self.iteration_history
        }
# ============================================================================
# ENHANCED WORKER AGENT
# ============================================================================
class EnhancedWorkerAgent:
    """Worker agent with intelligent context management"""

    def __init__(self, config, audit_logger, context_limits=None):
        self.config = config
        self.audit_logger = audit_logger
        self.context_manager = ContextManager(context_limits)

    def write_code(
        self,
        plan_data,
        feedback=None,
        iteration=1,
        previous_code=None,
        priority_fixes=None
    ):
        """Generate code with smart context management"""

        # Prepare optimized context
        prompt, metadata = self.context_manager.prepare_iteration_context(
            task=plan_data.get('task', ''),
            plan=plan_data.get('plan', ''),
            previous_code=previous_code,
            feedback=feedback,
            iteration=iteration,
            priority_fixes=priority_fixes
        )

        print("=" * 80)
        print(f"WORKER AGENT - Iteration {iteration}")
        print("=" * 80)
        print(f"📊 Context Stats:")
        print(f"   - Estimated tokens: {metadata['tokens_estimate']}")
        print(f"   - Includes previous code: {metadata['included_code']}")
        print(f"   - Includes feedback: {metadata['included_feedback']}")
        print()

        # Call AI API
        code, cost, tokens = call_ai_api_with_metrics(
            model_name=self.config.WORKER_MODEL,
            api_key=self.config.WORKER_API_KEY,
            prompt=prompt,
            temperature=0.2,
            config=self.config,
            audit_logger=self.audit_logger,
            agent_name="worker"
        )

        # Log iteration
        self.context_manager.log_iteration(
            iteration=iteration,
            prompt_tokens=tokens,
            code_length=len(code)
        )

        print(f"💰 Cost: ${cost:.6f} | Tokens: {tokens}")
        print()

        return code

    def get_context_summary(self):
        """Get context usage summary"""
        return self.context_manager.get_context_summary()
# ============================================================================
# ENHANCED ORCHESTRATOR
# ============================================================================
import ast
from dataclasses import asdict

class EnhancedCodingAgentOrchestrator:
    """Enhanced orchestrator with smart context management and pre-review syntax checking."""

    def __init__(
        self,
        config,
        max_iterations=3,
        max_redesigns=2,
        audit_log_file="agent_audit.jsonl",
        context_limits=None
    ):
        self.config = config
        self.max_iterations = max_iterations
        self.max_redesigns = max_redesigns

        # Initialize audit logger
        self.audit_logger = AuditLogger(audit_log_file)

        # Initialize agents
        self.planner = PlannerAgent(config, self.audit_logger)
        self.worker = EnhancedWorkerAgent(config, self.audit_logger, context_limits)
        self.reviewer = ReviewerAgent(config, self.audit_logger)

        # Cost tracking
        self.cost_metrics = CostMetrics()

    def _extract_and_validate_code(self, raw_code: str) -> tuple[bool, str, str]:
        """Extracts Python code from markdown and validates its syntax using AST."""
        clean_code = raw_code

        # 1. Strip Markdown formatting
        if "```python" in raw_code:
            try:
                start = raw_code.find("```python") + 9
                end = raw_code.find("```", start)
                if end != -1:
                    clean_code = raw_code[start:end].strip()
            except Exception:
                pass
        elif "```" in raw_code:
            try:
                start = raw_code.find("```") + 3
                end = raw_code.find("```", start)
                if end != -1:
                    clean_code = raw_code[start:end].strip()
            except Exception:
                pass

        clean_code = clean_code.strip()

        # 2. Validate Syntax
        try:
            ast.parse(clean_code)
            return True, clean_code, ""
        except SyntaxError as e:
            error_msg = f"SyntaxError on line {e.lineno}: {e.msg}\nCode snippet: {e.text}"
            return False, clean_code, error_msg

    def execute_task(self, task_description, codebase_context=""):
        """Execute task with smart context management and syntax validation."""

        print("🚀 STARTING ENHANCED AI CODING AGENT SYSTEM")
        print("=" * 80)
        print(f"Task: {task_description[:100]}...")
        print(f"Max Iterations: {self.max_iterations}")
        print(f"Max Redesigns: {self.max_redesigns}")
        print(f"Context Management & Pre-Review AST: ENABLED ✅")
        print()

        redesign_count = 0
        plan_data = None
        code = None

        # Redesign loop
        while redesign_count <= self.max_redesigns:

            if redesign_count == 0:
                print("📋 PHASE 1: INITIAL PLANNING")
                print("-" * 80)
                plan_data = self.planner.create_plan(task_description, codebase_context)
            else:
                print(f"🔄 ARCHITECTURAL REDESIGN #{redesign_count}")
                print("-" * 80)

            review_result = None

            # Iteration loop
            for iteration in range(1, self.max_iterations + 1):
                print(f"\n🔄 ITERATION {iteration}/{self.max_iterations}")
                print("-" * 80)

                # Extract priority fixes
                priority_fixes = None
                if review_result and review_result.get('critical_issues'):
                    priority_fixes = review_result['critical_issues']

                # Generate code with context management
                raw_code = self.worker.write_code(
                    plan_data=plan_data,
                    feedback=review_result.get('feedback') if review_result else None,
                    iteration=iteration,
                    previous_code=code,
                    priority_fixes=priority_fixes
                )

                # --- NEW: FAST-FEEDBACK SYNTAX CHECK ---
                is_valid, code, syntax_error = self._extract_and_validate_code(raw_code)

                if not is_valid:
                    print("\n" + "=" * 80)
                    print("🛑 SYNTAX ERROR DETECTED (Pre-Review Bypassed)")
                    print("=" * 80)
                    print(syntax_error)

                    # Create a "mock" review to instantly bounce it back to the Worker
                    review_result = {
                        'approved': False,
                        'needs_redesign': False,
                        'critical_issues': [f"FATAL: Invalid Python syntax: {syntax_error}"],
                        'feedback': f"Your code failed compilation. Fix this SyntaxError immediately:\n{syntax_error}",
                        'severity': 'CRITICAL' # Using string to match your enum mapping logic elsewhere
                    }

                    if iteration < self.max_iterations:
                        print(f"\n⚠️  Bouncing back to Worker. Continuing to iteration {iteration + 1}...")
                    continue # SKIP the ReviewerAgent entirely!

                # --- EXPENSIVE REVIEWER STEP (Only runs if syntax is valid) ---
                review_result = self.reviewer.review_code(
                    code=code,
                    original_task=task_description,
                    iteration=iteration
                )

                # Check if approved
                if review_result.get('approved'):
                    print("\n" + "=" * 80)
                    print("✅ CODE APPROVED - PRODUCTION READY!")
                    print("=" * 80)

                    return {
                        'final_code': code,
                        'review': review_result,
                        'iterations_used': iteration,
                        'redesigns_used': redesign_count,
                        'plan': plan_data.get('plan', ''),
                        'approved': True,
                        'status': 'SUCCESS',
                        'cost_metrics': {'total_cost': 0.0}, # Calculated elsewhere
                        'context_analytics': self.worker.get_context_summary()
                    }

                # Check if redesign needed
                elif review_result.get('needs_redesign'):
                    print("\n" + "=" * 80)
                    print("🚨 CRITICAL ARCHITECTURAL ISSUE DETECTED")
                    print("=" * 80)

                    redesign_feedback = f"""\nSEVERITY: {review_result.get('severity', 'CRITICAL')}\nCRITICAL ISSUES:\n{review_result.get('critical_issues', '')}\n\nFULL REVIEW:\n{review_result.get('feedback', '')}\n"""

                    plan_data = self.planner.create_plan(
                        task_description,
                        codebase_context,
                        redesign_feedback=redesign_feedback
                    )

                    redesign_count += 1
                    break

                else:
                    if iteration < self.max_iterations:
                        print(f"\n⚠️  Code needs revision. Continuing to iteration {iteration + 1}...")

            # Check if max iterations reached
            if iteration >= self.max_iterations and not (review_result and review_result.get('approved')):
                if redesign_count < self.max_redesigns:
                    print("\n⚠️  Max iterations reached, attempting redesign...")
                    redesign_count += 1
                else:
                    break

        # Max redesigns reached
        print("\n" + "=" * 80)
        print("⚠️  MAX REDESIGNS REACHED")
        print("=" * 80)

        return {
            'final_code': code,
            'review': review_result,
            'iterations_used': self.max_iterations,
            'redesigns_used': redesign_count,
            'plan': plan_data.get('plan', '') if plan_data else '',
            'approved': False,
            'status': 'FAILED - Exhausted Redesigns',
            'cost_metrics': {'total_cost': 0.0},
            'context_analytics': self.worker.get_context_summary()
        }
print("✅ ENHANCED CONTEXT MANAGEMENT SYSTEM LOADED!")
print()
print("🎯 New Features:")
print("  ✓ Smart context pruning (40-60% token reduction)")
print("  ✓ Previous code passing (AI sees what it wrote)")
print("  ✓ Focused feedback (only critical issues)")
print("  ✓ Context analytics tracking")
print()
print("📊 Usage:")
print("  config = APIConfig.from_keys(...)")
print("  agent = EnhancedCodingAgentOrchestrator(config=config)")
print("  result = agent.execute_task('Build a Flask API...')")
print("  print(result['context_analytics'])")

# ============================================================================
# TEST CELL - Enhanced System Test
# ============================================================================

# Step 1: Configure with your API keys
# IMPORTANT: Replace "Bearer YOUR_KEY_HERE" with your actual API keys.
config = APIConfig.from_env()

# Step 2: Create enhanced agent
agent = EnhancedCodingAgentOrchestrator(
    config=config,
    max_iterations=3,
    max_redesigns=2,
    context_limits=ContextLimits(
        max_prompt_tokens=6000,
        max_code_length=3000
    )
)

# ============================================================================
# FASTAPI BACKEND SERVER (THE BRAIN)
# ============================================================================

app = FastAPI(title="Sivan AI Backend")

# This is the master password users will need to type into their CLI!
SECRET_AUTH_CODE = os.getenv("SIVAN_AUTH_CODE", "SIVAN-BETA-777")

# Define what the CLI will send us
class TaskRequest(BaseModel):
    auth_code: str
    prompt: str

@app.post("/generate")
async def generate_code(request: TaskRequest):
    print(f"\n📩 Received new request from CLI!")
    
    # 1. The Bouncer: Check if they have the right password
    if request.auth_code != SECRET_AUTH_CODE:
        print("❌ Authentication failed. Wrong code.")
        raise HTTPException(status_code=401, detail="Invalid Authentication Code")
    
    print("✅ Authentication successful. Waking up Sivan...")
    
    try:
        # 2. Load your secure API keys from your .env vault
        config = APIConfig.from_env()
        
        # 3. Boot up the Orchestrator
        agent = EnhancedCodingAgentOrchestrator(
            config=config,
            max_iterations=3,
            max_redesigns=2
        )
        
        # 4. Run their prompt!
        result = agent.execute_task(request.prompt)
        
        # 5. Send ONLY the finished code back to their CLI
        return {
            "status": "success", 
            "code": result.get("final_code", "# Error: Sivan could not generate code.")
        }
        
    except Exception as e:
        print(f"❌ Server Error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

        
