# -*- coding: utf-8 -*-
"""SIVAN_CODE_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHj9DmJ23CkkxRGR9CMKz_H1GuU1TWmZ
"""

# @title
import requests
import json
import time
import os
from enum import Enum
from datetime import datetime
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, asdict
import hashlib
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

# =============================================================================
# CONFIGURATION & ENUMS
# =============================================================================

class Severity(Enum):
    CRITICAL = 3
    MEDIUM = 2
    MINOR = 1
    NONE = 0

class ReviewStatus(Enum):
    APPROVED = "APPROVED"
    NEEDS_REVISION = "NEEDS_REVISION"
    NEEDS_REDESIGN = "NEEDS_REDESIGN"

@dataclass
class APIConfig:
    """Secure API configuration - NO HARDCODED KEYS"""

    BASE_URL: str = "https://lightning.ai/api/v1/chat/completions"

    # Keys loaded securely
    PLANNER_API_KEY: str = None
    WORKER_API_KEY: str = None
    REVIEWER_API_KEY: str = None

    PLANNER_MODEL: str = "lightning-ai/gpt-oss-120b"
    WORKER_MODEL: str = "lightning-ai/nvidia-nemotron-3-nano-omni-30b-a3b"
    REVIEWER_MODEL: str = "openai/gpt-5.6-luna"

    COST_PER_1K_TOKENS: Dict[str, float] = None
    COST_PER_1M_TOKENS: Dict[str, Tuple[float, float]] = None

    def __post_init__(self):
        if self.COST_PER_1K_TOKENS is None:
            self.COST_PER_1K_TOKENS = {
                "lightning-ai/kimi-k2.5": 0.0001,
                "anthropic/claude-sonnet-4-5-20250929": 0.00014,
                # ADDED NEW MODELS HERE (using estimated pricing)
                "lightning-ai/gpt-oss-120b": 0.0007,
                "lightning-ai/nvidia-nemotron-3-nano-omni-30b-a3b": 0.0002,
                "openai/gpt-5.6-luna": 0.0050
            }

        # Format: "model_name": (Input_Price_Per_1M, Output_Price_Per_1M)
        if self.COST_PER_1M_TOKENS is None:
            self.COST_PER_1M_TOKENS = {
                "lightning-ai/gpt-oss-120b": (0.02, 0.10),
                "lightning-ai/nvidia-nemotron-3-nano-omni-30b-a3b": (0.25, 0.50),
                "openai/gpt-5.6-luna": (0.20, 1.20)
            }

    @classmethod
    def from_env(cls):
        """Load from environment (production)"""
        return cls(
            PLANNER_API_KEY=os.getenv("PLANNER_API_KEY"),
            WORKER_API_KEY=os.getenv("WORKER_API_KEY"),
            REVIEWER_API_KEY=os.getenv("REVIEWER_API_KEY")
        )

    @classmethod
    def from_keys(cls, planner_key: str, worker_key: str, reviewer_key: str):
        """Load from keys (development)"""
        return cls(
            PLANNER_API_KEY=planner_key,
            WORKER_API_KEY=worker_key,
            REVIEWER_API_KEY=reviewer_key
        )

# =============================================================================
# STRUCTURED RESPONSE MODELS
# =============================================================================

@dataclass
class ReviewResult:
    """Structured review - NO TEXT PARSING"""
    status: str
    severity: str
    critical_issues: List[str]
    medium_issues: List[str]
    minor_issues: List[str]
    architectural_concerns: List[str]
    specific_fixes: List[str]
    redesign_recommendation: Optional[str]
    positive_aspects: List[str]

    def to_dict(self):
        return asdict(self)

@dataclass
class CostMetrics:
    """Track API costs"""
    total_cost: float = 0.0
    planner_cost: float = 0.0
    worker_cost: float = 0.0
    reviewer_cost: float = 0.0
    total_tokens: int = 0
    total_latency: float = 0.0  # ADDED: Track cumulative latency

    # UPDATED SIGNATURE to include latency
    def add_cost(self, agent: str, tokens: int, cost: float, latency: float = 0.0):
        self.total_cost += cost
        self.total_tokens += tokens
        self.total_latency += latency  # ADDED: Accumulate latency
        if agent == "planner":
            self.planner_cost += cost
        elif agent == "worker":
            self.worker_cost += cost
        elif agent == "reviewer":
            self.reviewer_cost += cost

# =============================================================================
# AUDIT LOGGER
# =============================================================================

class AuditLogger:
    """Persistent audit logging"""

    def __init__(self, log_file: str = "agent_audit.jsonl"):
        self.log_file = log_file
        self.session_id = hashlib.md5(str(datetime.now()).encode()).hexdigest()[:8]

    def log(self, event_type: str, data: dict):
        entry = {
            "timestamp": datetime.now().isoformat(),
            "session_id": self.session_id,
            "event_type": event_type,
            "data": data
        }
        with open(self.log_file, "a") as f:
            f.write(json.dumps(entry) + "\n")

    def log_api_call(self, agent: str, model: str, prompt_length: int, response_length: int, cost: float):
        self.log("api_call", {
            "agent": agent,
            "model": model,
            "prompt_length": prompt_length,
            "response_length": response_length,
            "cost": cost
        })

    def log_iteration(self, iteration: int, status: str, severity: str):
        self.log("iteration", {"iteration": iteration, "status": status, "severity": severity})

    def log_redesign(self, redesign_count: int, reason: str):
        self.log("redesign", {"redesign_count": redesign_count, "reason": reason})

# =============================================================================
# RETRY & BACKOFF
# =============================================================================

def exponential_backoff_retry(func, max_retries: int = 3, base_delay: float = 1.0):
    """Retry with exponential backoff"""
    for attempt in range(max_retries):
        try:
            return func()
        except Exception as e:
            if attempt == max_retries - 1:
                raise
            delay = base_delay * (2 ** attempt)
            print(f"Retry {attempt + 1}/{max_retries} after {delay}s: {str(e)}")
            time.sleep(delay)

# =============================================================================
# API CALLER WITH METRICS
# =============================================================================

def call_ai_api_with_metrics(
    model_name: str,
    api_key: str,
    prompt: str,
    temperature: float,
    config: APIConfig,
    audit_logger: AuditLogger,
    agent_name: str,
    timeout: int = 300
) -> Tuple[str, float, int, float]:  # UPDATED RETURN TYPE TO INCLUDE FLOAT (LATENCY)
    """API call with timeout, retry, cost tracking, audit logging"""

    def api_call():
        start_time = time.time()  # START TIMER

        # Create the base payload that all models accept
        payload = {
            "model": model_name,
            "messages": [{"role": "user", "content": [{"type": "text", "text": prompt}]}],
            "temperature": 1.0
        }

        # Only add the extra beta parameters if it is NOT an Anthropic model
        if "anthropic" not in model_name.lower():
            payload["top_p"] = 1.0
            payload["n"] = 1
            payload["presence_penalty"] = 0.0
            payload["frequency_penalty"] = 0.0

        response = requests.post(
            url=config.BASE_URL,
            headers={"Authorization": api_key, "Content-Type": "application/json"},
            data=json.dumps(payload),
            timeout=timeout
        )

        if response.status_code != 200:
            raise Exception(f"API Error {response.status_code}: {response.text}")

        latency = time.time() - start_time  # STOP TIMER

        response_data = json.loads(response.content)

        if 'choices' in response_data:
            content = response_data['choices'][0]['message']['content']
        else:
            content = response_data.get('content', str(response_data))

        # 1. Separate input vs output tokens
        usage = response_data.get('usage', {})
        prompt_tokens = usage.get('prompt_tokens', len(prompt) // 4)
        completion_tokens = usage.get('completion_tokens', len(content) // 4)
        total_tokens = usage.get('total_tokens', prompt_tokens + completion_tokens)

        # 2. Extract precise pricing from the tuple
        input_rate, output_rate = config.COST_PER_1M_TOKENS.get(model_name, (0.0, 0.0))

        # 3. Calculate exact cost using per-1-million pricing
        cost = (prompt_tokens * (input_rate / 1_000_000)) + (completion_tokens * (output_rate / 1_000_000))

        audit_logger.log_api_call(agent_name, model_name, len(prompt), len(content), cost)

        # RETURN ALL 4 VALUES
        return content, cost, total_tokens, latency

    try:
        return exponential_backoff_retry(api_call)
    except Exception as e:
        print(f"CRITICAL: API failed: {str(e)}")
        return f"ERROR: {str(e)}", 0.0, 0, 0.0

# =============================================================================
# AGENTS
# =============================================================================

class PlannerAgent:
    """Architect and planner - DOES NOT GENERATE CODE"""

    def __init__(self, config: APIConfig, audit_logger: AuditLogger):
        self.config = config
        self.audit_logger = audit_logger

    def create_plan(self, task_description: str, codebase_context: str = "", redesign_feedback: Optional[str] = None) -> Dict:
        """Creates ONLY architectural plan - NO CODE GENERATION"""
        if redesign_feedback:
            prompt = f"""You are a SENIOR SOFTWARE ARCHITECT. Your role is PLANNING ONLY - NOT coding.

The previous implementation approach FAILED with these issues:
{redesign_feedback}

ORIGINAL TASK: {task_description}

YOUR JOB: Design a COMPLETELY DIFFERENT architectural approach.

⚠️ IMPORTANT: You are NOT writing code. You are making architectural decisions.

YOUR JOB: Design a COMPLETELY DIFFERENT architectural approach that follows the principle of PROPORTIONAL ENGINEERING.
- For trivial tasks: Prioritize clean, idiomatic, and robust single-file execution.
- For production tasks: Prioriti
